Fixes root checkbox being always checked when all children checkboxes…
vtex/styleguide pull request #1332
Opened 2020-10-01 14:46 UTC by tenorius-vtex

… are disabled

#### What is the purpose of this pull request?

As the title says...

#### What problem is this solving?

In the scenario of all children being disabled, as soon as the hook useCheckboxTree runs its `shake` effect, the error appears. 
This is caused because the Array.prototype.every method always returns true for empty arrays ([link](https://stackoverflow.com/questions/34137250/why-does-array-prototype-every-return-true-on-an-empty-array))

There are 2 ways of handling it: Just don't do anything or if the root checkbox is checked, uncheck it. 
I choose the latter, but I will leave it to the reviewers to decide the best approach.

#### How should this be manually tested?

[Running workspace](https://tenorio--bazarhorizonte.myvtex.com/admin/vtexlog/packing/?status=label_issued,carrier_notified)

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/70980489/94822304-de294d00-03d8-11eb-9450-f252b0b8dd41.png)
#### Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-10-07 14:14 UTC, estacioneto requested changes
I personally think that checking is different from disabling. But since this hook's logic might be completely guided using them as somehow equivalents, I think this fix can be enough.

Request changes just because of two little issues.

2020-10-07 14:14 UTC, estacioneto commented on react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
> +      const notDisabledChildNodes = childNodes.filter(
```suggestion
      const enabledChildren = childNodes.filter(
```

2020-10-07 14:14 UTC, estacioneto commented on react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Missing CHANGELOG.md entry

2020-10-07 20:04 UTC, estacioneto approved these changes

2020-10-08 13:15 UTC, guilhermebruzzi approved these changes

2020-10-08 13:30 UTC, merged