added new css handle for tag component
vtex/styleguide pull request #1354
Opened 2020-11-19 12:51 UTC by felipeireslan

#### What is the purpose of this pull request?

Add a css handle on `Tag` component to be able styling from store-theme.

#### What problem is this solving?

Adding this class we will be able to style Tag component through VTEX store-theme using css selectors.

[Running workspace](https://minicartcoupon--outletespacohering.myvtex.com/)

#### How should this be manually tested?

Add a product your cart, open minicart and add a coupon. After that you will see a Tag component used by [Coupon](https://github.com/vtex-apps/checkout-coupon) styled.

#### Screenshots or example usage

Example: https://prnt.sc/vm5ipo

#### Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-11-19 13:44 UTC, klzns requested changes
Thanks for the pull request! Just a minor correction in the changelog

2020-11-19 13:44 UTC, klzns commented on CHANGELOG.md
> +- added `vtex-tag` css in order to use css handles on store-theme.
```suggestion
- Class `vtex-tag` on `Tag` component.
```

2020-11-19 13:54 UTC, felipeireslan commented on CHANGELOG.md
> +- added `vtex-tag` css in order to use css handles on store-theme.
@klzns done.

2020-11-19 14:53 UTC, felipeireslan commented
@klzns done.

2020-11-19 15:50 UTC, klzns approved these changes

2020-11-25 12:57 UTC, matheusps approved these changes
LGTM

2020-11-26 12:36 UTC, estacioneto commented
Thank you for your contribution, @felipeireslan!
Since we're in a pretty critical moment (just before Black Friday), I'll release your PR and deploy it next week, ok? :)

2020-12-02 12:25 UTC, estacioneto commented
@felipeireslan can you please resolve the `CHANGELOG.md` conflicts? When you're done, we can release a new version :)

2020-12-03 18:36 UTC, felipeireslan commented
@estacioneto done. Can you please check again ?

2020-12-04 12:30 UTC, merged

2020-12-04 12:42 UTC, estacioneto commented
@felipeireslan just merged and release a new version here: #1355 . Will be deploying soon 🚀 
Thanks again for the contribution!