Fix getChartDefaultProps ignoring the user's chosen height property
vtex/styleguide pull request #1368
Opened 2021-02-24 17:34 UTC by tenorius-vtex

#### What is the purpose of this pull request?

#### What problem is this solving?

[Running workspace](http://link)

#### How should this be manually tested?

<details>
<summary>Add this code in <code>react/playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react'
import PageHeader from '../PageHeader'
import Layout from '../Layout'
const Playground = () => (
  <Layout fullWidth pageHeader={<PageHeader title="Playground" />}>
    {/* Add your code here, don't forget to delete after */}
  </Layout>
)
export default Playground
```

</details>

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-02-25 12:41 UTC, murilovarela reviewed
Doesn't it work passing `null` to override the `customConfig.container.aspect` during the loadash's `merge`?

2021-02-26 12:43 UTC, estacioneto requested changes
As we've discussed, it actually works passing `container: { aspect: null }` but it lacks documentation about the Styleguide's default aspect ratio.

Requesting this documentation here :)

2021-03-29 20:39 UTC, estacioneto approved these changes
✨

2021-03-30 14:34 UTC, murilovarela approved these changes

2021-03-30 18:30 UTC, merged